ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Decisiones arquitectónicas

En este apartado se tratarán de justificar las decisiones relacionadas con la arquitectura de la aplicación, de
una forma en la que se pueda comprender el porqué de cada una de ellas desde el punto de vista de cualquier usuario.

[cols="1,2"]
|===
|*Decisión*|*Justificación*
|_Git_ | Escogemos Git como sistema de control de versiones por ser la principal opción en el mercado y por ser un sistema
de control de versiones distribuido, lo que nos permite trabajar de forma más eficiente y simple.
|_GitHub_ | Se trata del servicio Git basado en la nube más popular y con más funcionalidades, lo que nos permite tener un control total
sobre los cambios de nuestra aplicación, además de tener la seguridad de que no vamos a perder ni una línea de código, aunque esta se sobreescriba en algún momento.
|_JavaScript_ | La mayor parte de integrantes del grupo tiene experiencia previa en este lenguaje, por lo que se conoce la versatilidad
y utilidad de este lenguaje para el desarrollo de aplicaciones web.
|_Docker_ | Principal opción para tener una implementación y despliegue rápidos de la aplicación. Permite desplegar aplicaciones y moverlas
con mucha facilidad, y cuenta con múltiples ejemplos para comprender su funcionamiento.
|_MongoDB_ | Es una de las principales soluciones del mercado, y ha sido elegida por su facilidad de uso y por la previa experiencia
de alguno de los componentes con esta base de datos.
|_Node.js_ | Se ha escogido por ser un entorno de ejecución para JavaScript en el servidor, con alto rendimiento y velocidad, ideal para aplicaciones web en tiempo real
como la que nos concierne.
|_React_ | Se ha escogido por ser una de las opciones más populares a la hora de desarrollar JavaScript con interfaces de usuario.
|_Wikidata_ | Esta era una opción clara por ser una base de datos libre, colaborativa y multilingüe, con la que conseguir la información para
las diferentes preguntas será muy sencillo.
|_Large Language Model (LLM)_ | Se utilizará para poder generar respuestas en tiempo real con el chatbot de inteligencia artificial que
se implementará en la aplicación.
|_Plantilla Arc42_ | Se ha escogido esta plantilla por ser una de las más completas y por tener una estructura clara y sencilla de seguir,
permitiendo al lector entender de un vistazo qué es lo que está viendo, y encontrar con facilidad los diferentes apartados de la estructura.
|===



ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions," we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****
endif::arc42help[]
